name: hashpro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  hooks_riverpod: ^2.1.1
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.4
  cloud_firestore: ^4.0.4
  uuid: ^3.0.6
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  image: ^3.2.2
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  intl: ^0.17.0
  video_thumbnail: ^0.5.3
  video_player: ^2.4.7
  lottie: ^1.4.3
  share_plus: ^6.2.0
  url_launcher: ^6.1.6
  firebase_database: ^10.0.6
  percent_indicator: ^4.2.2
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  audioplayers: ^1.1.1
  file_picker: ^5.2.2
  esp_smartconfig: ^1.1.10
  esptouch_flutter: ^1.0.0
  fl_chart: ^0.55.2
  calendar_date_picker2: ^0.3.5
  ffmpeg_kit_flutter: ^5.1.0
  record_mp3: ^3.0.0
  path_provider: ^2.0.11
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  