// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7nN8n9THIGGiV0gd20oPsLGvcyf5w5o',
    appId: '1:775052237529:web:3bb4fd2bb15a14cd653cc8',
    messagingSenderId: '775052237529',
    projectId: 'adhd-helper-bdfeb',
    authDomain: 'adhd-helper-bdfeb.firebaseapp.com',
    databaseURL: 'https://adhd-helper-bdfeb-default-rtdb.firebaseio.com',
    storageBucket: 'adhd-helper-bdfeb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjgxblauE_eisioCfOEiG79rz_W6RbaQU',
    appId: '1:775052237529:android:8012de2db71c426c653cc8',
    messagingSenderId: '775052237529',
    projectId: 'adhd-helper-bdfeb',
    databaseURL: 'https://adhd-helper-bdfeb-default-rtdb.firebaseio.com',
    storageBucket: 'adhd-helper-bdfeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUyRoTTJUDbH6Gmp6CkIksy_0YkqM1wek',
    appId: '1:775052237529:ios:b8f837a0c3216712653cc8',
    messagingSenderId: '775052237529',
    projectId: 'adhd-helper-bdfeb',
    databaseURL: 'https://adhd-helper-bdfeb-default-rtdb.firebaseio.com',
    storageBucket: 'adhd-helper-bdfeb.appspot.com',
    iosClientId: '775052237529-4mv0csp1svofh9ourd5burmudm94v4jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.adhdHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUyRoTTJUDbH6Gmp6CkIksy_0YkqM1wek',
    appId: '1:775052237529:ios:b8f837a0c3216712653cc8',
    messagingSenderId: '775052237529',
    projectId: 'adhd-helper-bdfeb',
    databaseURL: 'https://adhd-helper-bdfeb-default-rtdb.firebaseio.com',
    storageBucket: 'adhd-helper-bdfeb.appspot.com',
    iosClientId: '775052237529-4mv0csp1svofh9ourd5burmudm94v4jk.apps.googleusercontent.com',
    iosBundleId: 'com.example.adhdHelper',
  );
}
